### ISSUE TITLE
Unable to test the code

### ISSUE THREAD

**Issue by Zumbalamambo** [hellochick/Indoor-segmentation#1]
Im getting the following error while trying to run the code

```
File "inference.py", line 128, in <module>
    main()
  File "inference.py", line 85, in main
    net = DeepLabResNetModel({'data': tf.expand_dims(img, dim=0)}, is_training=False, num_classes=NUM_CLASSES)
  File "/Users/Downloads/Indoor-segmentation-master/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/Users/Downloads/Indoor-segmentation-master/model.py", line 19, in setup
    (self.feed('data')
  File "/Users/Downloads/Indoor-segmentation-master/network.py", line 78, in feed
    if isinstance(fed_layer, basestring):
NameError: name 'basestring' is not defined
```

**Comment by hellochick** [comment]
Since this code is for python 2.7, you can replace 'basestring' with 'str' in network.py to solve it.
If you have other problems, feel free to tell me !

**Comment by Zumbalamambo** [comment]
okay...thank you... I tried running like the following 

`python inference.py --img_path="person.jpg" --restore-from="restore_weights"`

but im getting the following error,

> 
> usage: inference.py [-h] [--img_path IMG_PATH] [--restore_from RESTORE_FROM]
> inference.py: error: unrecognized arguments: --restore-from=restore_weights

**Comment by hellochick** [comment]
Oh, It's my typo. I accidentally wrote 'restore_from' into 'restore-from' 
You can try
`python inference.py --img_path=./person.jpg --restore_from=./restore_weights`
If your photo placed in "input" folder, then try ./input/person.jpg

**Comment by Zumbalamambo** [comment]
again it throws the following error,

```
Traceback (most recent call last):
  File "inference.py", line 128, in <module>
    main()
  File "inference.py", line 85, in main
    net = DeepLabResNetModel({'data': tf.expand_dims(img, dim=0)}, is_training=False, num_classes=NUM_CLASSES)
  File "/Users/Downloads/Indoor-segmentation-master/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/Users/Downloads/Indoor-segmentation-master/model.py", line 20, in setup
    .conv(7, 7, 64, 2, 2, biased=False, relu=False, name='conv1')
  File "/Users/Downloads/Indoor-segmentation-master/network.py", line 22, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/Users/Downloads/Indoor-segmentation-master/network.py", line 128, in conv
    kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'
```

**Comment by hellochick** [comment]
I think these problem happened because version of Python 
Maybe you can try to run this code in python 2.7 
Or you will need to do a bunch of small trick to make it work in Python 3.6.

For this problem:
change it to:
`kernel = self.make_var('weights', shape=[k_h, k_w, int(c_i) / group, c_o])`

**Comment by ivanonair** [comment]
hello, I would like to know is there a way to run it on python 3.x?
